### ISSUE TITLE
#addMessage: on CascadeNode is misleading 

### ISSUE THREAD

**Issue by Larcheveque** [juliendelplanque/PharoCodeGenerator#7]
Maybe it should define the receiver of the MessageNode provided with the target of the cascade

**Comment by Larcheveque** [comment]
Not sure because i do not know the structure well but maybe the CascadeNode should have a dedicated MessageNode

**Comment by juliendelplanque** [comment]
I fixed this by modifyingg #addMessage: as:

```Smalltalk
addMessage: aMessageNode
	aMessageNode receiver: self target.
	self messages add: aMessageNode
```
